---

- name: Télécharger la clé PostgreSQL
  command: "wget -O /usr/share/keyrings/postgresql.asc https://www.postgresql.org/media/keys/ACCC4CF8.asc"

- name: Ajouter la source APT pour PostgreSQL
  command: "echo 'deb [signed-by=/usr/share/keyrings/postgresql.asc] http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main' > /etc/apt/sources.list.d/postgresql.list"

- name: Mettre à jour la liste des paquets 
  apt:
    update_cache: yes

- name: Installer PostgreSQL
  apt:
    name: postgresql
    state: present







    

