---
- name: installation de mastodon
  hosts: web
  become: true
  roles:
  - roles/ssh
  - roles/key-ssh
  - roles/python3
  - roles/smtp
  - roles/nodejs
  - roles/postgresql
  - roles/system-packages
  - roles/nodejs
  - roles/enable-corepack
  - roles/ruby
  - roles/configuration-postgresql
  - roles/mastodon-setup

  