---
# tasks file for configuration-postgresql
- name: Configure PostgreSQL
  become: true
  become_user: root
  lineinfile:
    path: /etc/postgresql/15/main/postgresql.conf
    regexp: "^#?{{ item.name }}\\s*="
    line: "{{ item.name }} = {{ item.value }}"
  with_items:
    - { name: 'shared_buffers', value: '512MB' }
    - { name: 'effective_cache_size', value: '2GB' }
    # Ajoutez d'autres paramètres de configuration au besoin

- name: Restart PostgreSQL
  systemd:
    name: postgresql
    state: restarted

- name: Create PostgreSQL User for Mastodon
  become: true
  become_user: root
  postgresql_user:
    db: postgres
    name: mastodon
    password: "password"
    role_attr_flags: CREATEDB

