---
- name: Update apt cache (for Ubuntu/Debian)
  apt:
    update_cache: yes

- name: Install openssh-server
  become: true
  package:
    name: openssh-server
    state: present

- name: Start and enable ssh service
  become: true
  service:
    name: ssh
    state: started
    enabled: yes





