---

# A exécuter avec :
# ansible-playbook --ask-pass playbook-ssh.yml
# ansible -m authorized_key -a "user=openit state=present key={{ lookup('file', '~/.ssh/id_ed25519.pub') }}" --ask-pass all

- name: Configurer la connexion SSH avec une clé
  become: true
  authorized_key:
    user: "{{ ssh_user }}"
    key: "{{ lookup('file', ssh_public_key_path) }}"
    state: present